[build]
  publish = "public"
  command = "npm run build"
  functions = "functions"

[dev]
  command = "npm start"
  port = 8888
  publish = "public"

[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/socketio-server/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 